FROM python:3.14-slim-bookworm
COPY --from=ghcr.io/astral-sh/uv:0.9.7 /uv /bin/uv
WORKDIR /opt/replace_fonts
COPY requirements_dev.txt .
RUN uv pip install --system --no-cache-dir -r requirements_dev.txt
COPY replace_fonts.py .
WORKDIR /work
ENV HOME=/tmp
ENV PYTHONPATH=/opt/replace_fonts:/work
ENV PYTHONDONTWRITEBYTECODE=1
CMD ["/bin/bash"]
