FROM python:3.14-slim-bookworm
COPY requirements_dev.txt /requirements_dev.txt
# hadolint ignore=DL3013
RUN python -m pip install --no-cache-dir --upgrade pip && python -m pip install --no-cache-dir -r /requirements_dev.txt
COPY replace_fonts.py /replace_fonts.py
WORKDIR /work
ENV HOME=/tmp
CMD ["/bin/bash"]
