FROM python:3.14-slim-bookworm
COPY --from=ghcr.io/astral-sh/uv:0.9.2 /uv /bin/uv
COPY requirements_dev.txt /requirements_dev.txt
RUN uv pip install --system --no-cache-dir -r /requirements_dev.txt
COPY replace_fonts.py /replace_fonts.py
WORKDIR /work
ENV HOME=/tmp
CMD ["/bin/bash"]
