#!/bin/bash
set -eu -o pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
readonly SCRIPT_DIR

if command -v docker &>/dev/null; then
  docker container run \
    --name replace_fonts$$ \
    --rm \
    -t \
    -u "$(id -u):$(id -g)" \
    -v "$PWD":/work \
    ghcr.io/shakiyam/replace_fonts "$@"
elif command -v podman &>/dev/null; then
  podman container run \
    --name replace_fonts$$ \
    --rm \
    --security-opt label=disable \
    -t \
    -v "$PWD":/work \
    ghcr.io/shakiyam/replace_fonts "$@"
elif command -v python3 &>/dev/null; then
  python3 "$SCRIPT_DIR"/replace_fonts.py "$@"
elif command -v python &>/dev/null; then
  python "$SCRIPT_DIR"/replace_fonts.py "$@"
fi
