#!/bin/bash
set -Eeu -o pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
readonly SCRIPT_DIR

if command -v docker &>/dev/null; then
  docker container run \
    --name "replace_fonts_dev_$(uuidgen | head -c8)" \
    --rm \
    -it \
    -u "$(id -u):$(id -g)" \
    -v "$PWD":/work \
    -v "$SCRIPT_DIR"/replace_fonts.py:/replace_fonts.py \
    ghcr.io/shakiyam/replace_fonts_dev "$@"
elif command -v podman &>/dev/null; then
  podman container run \
    --name "replace_fonts_dev_$(uuidgen | head -c8)" \
    --rm \
    --security-opt label=disable \
    -it \
    -v "$PWD":/work \
    -v "$SCRIPT_DIR"/replace_fonts.py:/replace_fonts.py \
    ghcr.io/shakiyam/replace_fonts_dev "$@"
fi
