#!/bin/bash
set -eu -o pipefail

if [[ $(command -v docker) ]]; then
  docker container run \
    --name replace_fonts$$ \
    --rm \
    -t \
    -u "$(id -u):$(id -g)" \
    -v "$PWD":/work \
    ghcr.io/shakiyam/replace_fonts "$@"
else
  podman container run \
    --name replace_fonts$$ \
    --rm \
    --security-opt label=disable \
    -t \
    -v "$PWD":/work \
    ghcr.io/shakiyam/replace_fonts "$@"
fi
