#!/bin/bash
set -Eeu -o pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
readonly SCRIPT_DIR

if [[ -t 0 ]]; then
  TTY_FLAGS="-t"
else
  TTY_FLAGS=""
fi

if command -v docker &>/dev/null; then
  docker container run \
    --name "replace_fonts_dev_$(uuidgen | head -c8)" \
    --rm \
    -i \
    $TTY_FLAGS \
    -u "$(id -u):$(id -g)" \
    -v "$PWD":/work \
    -v "$SCRIPT_DIR"/replace_fonts.py:/opt/replace_fonts/replace_fonts.py \
    ghcr.io/shakiyam/replace_fonts_dev "$@"
elif command -v podman &>/dev/null; then
  podman container run \
    --name "replace_fonts_dev_$(uuidgen | head -c8)" \
    --rm \
    --security-opt label=disable \
    -i \
    $TTY_FLAGS \
    -v "$PWD":/work \
    -v "$SCRIPT_DIR"/replace_fonts.py:/opt/replace_fonts/replace_fonts.py \
    ghcr.io/shakiyam/replace_fonts_dev "$@"
fi
