#!/bin/bash
set -Eeu -o pipefail

if git diff --cached --name-only | grep -q "replace_fonts.py"; then
  VERSION_DATE=$(date +%Y-%m-%d)
  sed -i "s/^__version__ = \".*\"/__version__ = \"$VERSION_DATE\"/" replace_fonts.py
  git add replace_fonts.py
fi
